from django.db import models

# Create your models here.


class Category(models.Model):
    wb_id = models.IntegerField()
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=255)
    path = models.CharField(max_length=255)
    url = models.URLField()
    sales = models.IntegerField(null=True, blank=True)
    revenue = models.IntegerField(null=True, blank=True)
    items = models.IntegerField(null=True, blank=True)
    items_with_sells = models.IntegerField(null=True, blank=True)
    items_with_sells_percent = models.IntegerField(null=True, blank=True)
    sellers = models.IntegerField(null=True, blank=True)
    sellers_with_sells = models.IntegerField(null=True, blank=True)
    brands = models.IntegerField(null=True, blank=True)
    brands_with_sells = models.IntegerField(null=True, blank=True)
    sellers_with_sells_percent = models.IntegerField(null=True, blank=True)
    sales_per_items_average = models.IntegerField(null=True, blank=True)
    revenue_per_items_average = models.IntegerField(null=True, blank=True)
    avg_price = models.IntegerField(null=True, blank=True)
    median_price = models.IntegerField(null=True, blank=True)
    rating = models.IntegerField(null=True, blank=True)
    comments = models.IntegerField(null=True, blank=True)
    balance = models.IntegerField(null=True, blank=True)
    live_items = models.IntegerField(null=True, blank=True)
    revenue_potential = models.IntegerField(null=True, blank=True)
    lost_profit = models.IntegerField(null=True, blank=True)
    lost_profit_percent = models.IntegerField(null=True, blank=True)
    graph = models.JSONField(null=True, blank=True)
    commision_fbo = models.IntegerField(null=True, blank=True)
    commision_fbs = models.IntegerField(null=True, blank=True)
    basic_logistics = models.IntegerField(null=True, blank=True)
    storage_price = models.IntegerField(null=True, blank=True)
    acceptance_price = models.IntegerField(null=True, blank=True)
    delivery_by_volume = models.IntegerField(null=True, blank=True)
    purchase = models.IntegerField(null=True, blank=True)
    purchase_after_return = models.IntegerField(null=True, blank=True)
