version: "3.3"

services:
  # db:
  #   image: postgres
  #   ports:
  #     - '5432:5432'
  #   environment:
  #     POSTGRES_DB: 'gh'
  #     POSTGRES_USER: 'ghuser'
  #     POSTGRES_PASSWORD: 'ghpassword'
  #   restart: always
  #   volumes:
  #     - ./data/db:/var/lib/postgres
  # db:
  #   image: postgres
  #   shm_size: 4g
  #   restart: always
  #   command:
  #     - "postgres"
  #     - "-c"
  #     - "max_connections=50"
  #     - "-c"
  #     - "shared_buffers=4GB"
  #     - "-c"
  #     - "effective_cache_size=4GB"
  #     - "-c"
  #     - "maintenance_work_mem=512MB"
  #     - "-c"
  #     - "temp_file_limit=10GB"
  #   ports:
  #     - '5432:5432'
  #   volumes:
  #     - ./data/db:/var/lib/postgresql/data
  #   environment:
  #     # - "POSTGRES_HOST_AUTH_METHOD=trust"
  #     - POSTGRES_DB=gh
  #     - POSTGRES_USER=ghuser
  #     - POSTGRES_PASSWORD=ghpassworde23f8852aa92
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '2'
  #         memory: 4G
  web:
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    extra_hosts:
      - 'db:172.17.0.1'
