# Generated by Django 4.2.7 on 2024-03-01 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wb_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('sales', models.IntegerField()),
                ('revenue', models.IntegerField()),
                ('items', models.IntegerField()),
                ('items_with_sells', models.IntegerField()),
                ('items_with_sells_percent', models.IntegerField()),
                ('sellers', models.IntegerField()),
                ('sellers_with_sells', models.IntegerField()),
                ('brands', models.IntegerField()),
                ('brands_with_sells', models.IntegerField()),
                ('sellers_with_sells_percent', models.IntegerField()),
                ('sales_per_items_average', models.IntegerField()),
                ('revenue_per_items_average', models.IntegerField()),
                ('avg_price', models.IntegerField()),
                ('median_price', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('comments', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('live_items', models.IntegerField()),
                ('revenue_potential', models.IntegerField()),
                ('lost_profit', models.IntegerField()),
                ('lost_profit_percent', models.IntegerField()),
                ('graph', models.JSONField()),
                ('commision_fbo', models.IntegerField()),
                ('commision_fbs', models.IntegerField()),
                ('basic_logistics', models.IntegerField()),
                ('storage_price', models.IntegerField()),
                ('acceptance_price', models.IntegerField()),
                ('delivery_by_volume', models.IntegerField()),
                ('purchase', models.IntegerField()),
                ('purchase_after_return', models.IntegerField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mpstats.category')),
            ],
        ),
    ]
