# Generated by Django 4.2.7 on 2024-03-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpstats', '0002_alter_category_acceptance_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='wb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
