# Generated by Django 4.2.7 on 2024-03-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpstats', '0003_alter_category_wb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=1020),
        ),
        migrations.AlterField(
            model_name='category',
            name='path',
            field=models.CharField(max_length=1020),
        ),
    ]
