# Generated by Django 4.2.7 on 2024-03-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpstats', '0004_alter_category_name_alter_category_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='category',
            name='path',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.CharField(max_length=2048),
        ),
    ]
