# Generated by Django 4.2.7 on 2024-05-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpstats', '0005_alter_category_name_alter_category_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoring', models.IntegerField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
