# Generated by Django 4.2.7 on 2024-05-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpstats', '0006_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['-scoring']},
        ),
        migrations.AddField(
            model_name='subject',
            name='mpstats_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
