# Generated by Django 4.1.5 on 2023-01-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="subscribe_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
