# Generated by Django 4.1.5 on 2023-01-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_customer_subscribe_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="phone",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
