# Generated by Django 4.1.5 on 2023-02-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order", name="paid", field=models.BooleanField(default=False),
        ),
    ]
