# Generated by Django 4.1.5 on 2023-02-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_order_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="amount",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
