# Generated by Django 4.1.7 on 2023-03-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_category_config_product_sale_query'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='first_product_decada_profit',
        ),
        migrations.RemoveField(
            model_name='category',
            name='first_product_decada_sales',
        ),
        migrations.RemoveField(
            model_name='category',
            name='ten_product_decada_profit',
        ),
        migrations.RemoveField(
            model_name='category',
            name='ten_product_decada_sales',
        ),
        migrations.RemoveField(
            model_name='config',
            name='current_parsing_date',
        ),
        migrations.AddField(
            model_name='category',
            name='mongo_id',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='mongo_id',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='parsing_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='thread_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='mongo_id',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='mongo_id',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='current_parsing_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parsed_at'], name='api_categor_parsed__e0f9df_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['articul'], name='api_product_articul_7f302c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category_wb_id'], name='api_product_categor_50ede3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['categories'], name='api_product_categor_0817dc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['queries'], name='api_product_queries_2e988b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['parsed_at'], name='api_product_parsed__204a0c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['root'], name='api_product_root_6de3c2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['hom_sales_growth'], name='api_product_hom_sal_79b9a4_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-sales'], name='api_product_sales_e6e7e7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category_id', 'last_parsing_id'], name='api_product_categor_7d13ab_idx'),
        ),
        migrations.AddIndex(
            model_name='query',
            index=models.Index(fields=['current_parsing_id'], name='api_query_current_5fd99c_idx'),
        ),
    ]
