# Generated by Django 4.1.7 on 2023-03-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_category_first_product_decada_profit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='parsing_date',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
