# Generated by Django 4.1.7 on 2023-03-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_category_seo_alter_category_shard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='mongo_category_id',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
