# Generated by Django 4.1.7 on 2023-03-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_query_mongo_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='mongo_category_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='mongo_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
