# Generated by Django 4.1.7 on 2023-03-20 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_query_mongo_category_id_alter_query_mongo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
    ]
