# Generated by Django 4.1.7 on 2023-03-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_query_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mongo_category_id',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
