# Generated by Django 4.1.7 on 2023-03-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_product_mongo_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales_count',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
