# Generated by Django 4.1.7 on 2023-03-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_wb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
