# Generated by Django 4.1.7 on 2023-03-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_sale_date_alter_sale_price_alter_sale_profit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='category',
            name='first_product_profit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='first_product_sales',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='ten_product_profit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='ten_product_sales',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['current_hom_sales'], name='api_product_current_188e5e_idx'),
        ),
    ]
