# Generated by Django 4.1.7 on 2023-04-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_sale_options_category_first_product_profit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='first_product_profit',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='profit_period',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='profit_prev_period',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='sales_period',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='ten_product_profit',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
