# Generated by Django 4.1.7 on 2023-04-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_category_first_product_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='wb_query',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
