# Generated by Django 4.1.7 on 2023-04-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_category_wb_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='wb_query',
            field=models.CharField(max_length=1000),
        ),
    ]
