# Generated by Django 4.1.7 on 2023-04-07 07:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_category_wb_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), size=None), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='features',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='queries',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), size=None), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='query',
            name='articuls',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), size=None), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='query',
            name='features',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None), default=[], size=None),
        ),
    ]
