# Generated by Django 4.2 on 2023-04-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_product_categories_alter_product_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mongo_transfered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['-date'], name='api_sale_date_b2477e_idx'),
        ),
    ]
