# Generated by Django 4.1.7 on 2023-04-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_product_categories_alter_product_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='parsed_at',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
