# Generated by Django 4.2 on 2023-04-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_product_mongo_transfered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='profit',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
