# Generated by Django 4.2 on 2023-04-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_sale_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='current_hom_profit',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_hom_profit',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
