# Generated by Django 4.2 on 2023-04-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_product_current_hom_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='profit_fbo',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='profit_fbs',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='sales_fbo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='sales_fbs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
