# Generated by Django 4.2 on 2023-04-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_sale_profit_fbo_sale_profit_fbs_sale_sales_fbo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sales_count',
            new_name='quantity_fbo',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_fbs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_fbo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_fbs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='quantity_fbo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='quantity_fbs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
