# Generated by Django 4.2 on 2023-05-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_rename_sales_count_product_quantity_fbo_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='api_product_categor_50ede3_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='api_product_queries_2e988b_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='api_product_root_6de3c2_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='api_product_hom_sal_79b9a4_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='api_product_categor_7d13ab_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='queries',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['root', 'features'], name='api_product_root_91d42c_idx'),
        ),
    ]
