# Generated by Django 4.2 on 2023-05-05 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_product_api_product_categor_50ede3_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='mongo_category_id',
        ),
    ]
