# Generated by Django 4.2 on 2023-05-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_product_mongo_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='first_product_hom_profit',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='profit_period',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='profit_prev_period',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='ten_product_hom_profit',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
