# Generated by Django 4.2 on 2023-05-10 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_query_first_product_hom_profit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('period', models.IntegerField()),
                ('fb', models.CharField(max_length=3)),
                ('product_first_profit', models.BigIntegerField(blank=True, null=True)),
                ('product_ten_profit', models.BigIntegerField(blank=True, null=True)),
                ('products_price', models.IntegerField(blank=True, null=True)),
                ('products_count', models.IntegerField(blank=True, null=True)),
                ('products_solded', models.IntegerField(blank=True, null=True)),
                ('products_solded_rel', models.IntegerField(blank=True, null=True)),
                ('sellers_solded_rel', models.IntegerField(blank=True, null=True)),
                ('products_profit', models.BigIntegerField(blank=True, null=True)),
                ('top', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parsing_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('quantity_fbo', models.IntegerField(blank=True, default=0, null=True)),
                ('quantity_fbs', models.IntegerField(blank=True, default=0, null=True)),
                ('sales_fbo', models.IntegerField(blank=True, default=0, null=True)),
                ('sales_fbs', models.IntegerField(blank=True, default=0, null=True)),
                ('sales_7_fbo', models.IntegerField(blank=True, default=0, null=True)),
                ('sales_7_fbs', models.IntegerField(blank=True, default=0, null=True)),
                ('sales_14_fbo', models.IntegerField(blank=True, default=0, null=True)),
                ('sales_14_fbs', models.IntegerField(blank=True, default=0, null=True)),
                ('sales_30_fbo', models.IntegerField(blank=True, default=0, null=True)),
                ('sales_30_fbs', models.IntegerField(blank=True, default=0, null=True)),
                ('profit_fbo', models.BigIntegerField(blank=True, default=0, null=True)),
                ('profit_fbs', models.BigIntegerField(blank=True, default=0, null=True)),
                ('profit_7_fbo', models.BigIntegerField(blank=True, default=0, null=True)),
                ('profit_7_fbs', models.BigIntegerField(blank=True, default=0, null=True)),
                ('profit_14_fbo', models.BigIntegerField(blank=True, default=0, null=True)),
                ('profit_14_fbs', models.BigIntegerField(blank=True, default=0, null=True)),
                ('profit_30_fbo', models.BigIntegerField(blank=True, default=0, null=True)),
                ('profit_30_fbs', models.BigIntegerField(blank=True, default=0, null=True)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='api_product_sales_e6e7e7_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='api_product_current_188e5e_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_wb_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='current_hom_profit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='current_hom_sales',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hom_profit_growth',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hom_sales_growth',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='product',
            name='last_hom_profit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='last_hom_sales',
        ),
        migrations.RemoveField(
            model_name='product',
            name='last_parsing_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mongo_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mongo_transfered',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_fbo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_fbs',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sales',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sales_fbo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sales_fbs',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subject_id',
        ),
        migrations.RemoveField(
            model_name='query',
            name='mongo_category_id',
        ),
        migrations.RemoveField(
            model_name='query',
            name='mongo_id',
        ),
        migrations.AddField(
            model_name='config',
            name='parsed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productstat',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
        migrations.AddField(
            model_name='categorystat',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
    ]
