# Generated by Django 4.2 on 2023-05-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_categorystat_productstat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productstat',
            options={'ordering': ['-parsing_id']},
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='api_categor_parsed__e0f9df_idx',
        ),
        migrations.RemoveIndex(
            model_name='query',
            name='api_query_current_5fd99c_idx',
        ),
        migrations.RemoveField(
            model_name='category',
            name='avg_price_period',
        ),
        migrations.RemoveField(
            model_name='category',
            name='avg_price_prev_period',
        ),
        migrations.RemoveField(
            model_name='category',
            name='avg_price_top',
        ),
        migrations.RemoveField(
            model_name='category',
            name='calculated',
        ),
        migrations.RemoveField(
            model_name='category',
            name='first_product_price',
        ),
        migrations.RemoveField(
            model_name='category',
            name='first_product_profit',
        ),
        migrations.RemoveField(
            model_name='category',
            name='first_product_profit_top',
        ),
        migrations.RemoveField(
            model_name='category',
            name='first_product_sales',
        ),
        migrations.RemoveField(
            model_name='category',
            name='products_count',
        ),
        migrations.RemoveField(
            model_name='category',
            name='products_with_sales',
        ),
        migrations.RemoveField(
            model_name='category',
            name='profit_period',
        ),
        migrations.RemoveField(
            model_name='category',
            name='profit_prev_period',
        ),
        migrations.RemoveField(
            model_name='category',
            name='profit_top',
        ),
        migrations.RemoveField(
            model_name='category',
            name='rel_sales',
        ),
        migrations.RemoveField(
            model_name='category',
            name='rel_sales_top',
        ),
        migrations.RemoveField(
            model_name='category',
            name='rel_sellers',
        ),
        migrations.RemoveField(
            model_name='category',
            name='sales_period',
        ),
        migrations.RemoveField(
            model_name='category',
            name='sellers',
        ),
        migrations.RemoveField(
            model_name='category',
            name='sellers_with_sales',
        ),
        migrations.RemoveField(
            model_name='category',
            name='ten_product_price',
        ),
        migrations.RemoveField(
            model_name='category',
            name='ten_product_profit',
        ),
        migrations.RemoveField(
            model_name='category',
            name='ten_product_profit_top',
        ),
        migrations.RemoveField(
            model_name='category',
            name='ten_product_sales',
        ),
        migrations.RemoveField(
            model_name='category',
            name='top',
        ),
        migrations.RemoveField(
            model_name='categorystat',
            name='fb',
        ),
        migrations.RemoveField(
            model_name='categorystat',
            name='period',
        ),
        migrations.RemoveField(
            model_name='categorystat',
            name='product_first_profit',
        ),
        migrations.RemoveField(
            model_name='categorystat',
            name='product_ten_profit',
        ),
        migrations.RemoveField(
            model_name='categorystat',
            name='products_price',
        ),
        migrations.RemoveField(
            model_name='categorystat',
            name='products_profit',
        ),
        migrations.RemoveField(
            model_name='categorystat',
            name='products_solded',
        ),
        migrations.RemoveField(
            model_name='categorystat',
            name='products_solded_rel',
        ),
        migrations.RemoveField(
            model_name='categorystat',
            name='sellers_solded_rel',
        ),
        migrations.RemoveField(
            model_name='categorystat',
            name='top',
        ),
        migrations.RemoveField(
            model_name='query',
            name='articuls',
        ),
        migrations.RemoveField(
            model_name='query',
            name='avg_price_period',
        ),
        migrations.RemoveField(
            model_name='query',
            name='avg_price_prev_period',
        ),
        migrations.RemoveField(
            model_name='query',
            name='avg_price_top',
        ),
        migrations.RemoveField(
            model_name='query',
            name='current_parsing_id',
        ),
        migrations.RemoveField(
            model_name='query',
            name='first_product_hom_profit',
        ),
        migrations.RemoveField(
            model_name='query',
            name='first_product_profit_top',
        ),
        migrations.RemoveField(
            model_name='query',
            name='last_parsed_page',
        ),
        migrations.RemoveField(
            model_name='query',
            name='parsed_at',
        ),
        migrations.RemoveField(
            model_name='query',
            name='products_with_sales',
        ),
        migrations.RemoveField(
            model_name='query',
            name='products_with_sales_top',
        ),
        migrations.RemoveField(
            model_name='query',
            name='profit_period',
        ),
        migrations.RemoveField(
            model_name='query',
            name='profit_prev_period',
        ),
        migrations.RemoveField(
            model_name='query',
            name='profit_top',
        ),
        migrations.RemoveField(
            model_name='query',
            name='rel_products_with_sales',
        ),
        migrations.RemoveField(
            model_name='query',
            name='rel_sales_top',
        ),
        migrations.RemoveField(
            model_name='query',
            name='sales_period',
        ),
        migrations.RemoveField(
            model_name='query',
            name='sellers',
        ),
        migrations.RemoveField(
            model_name='query',
            name='sellers_with_sales',
        ),
        migrations.RemoveField(
            model_name='query',
            name='ten_product_hom_profit',
        ),
        migrations.RemoveField(
            model_name='query',
            name='ten_product_profit_top',
        ),
        migrations.RemoveField(
            model_name='query',
            name='top',
        ),
        migrations.AddField(
            model_name='categorystat',
            name='parsing_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorystat',
            name='price_avg_14',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorystat',
            name='price_avg_30',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorystat',
            name='price_avg_7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorystat',
            name='products_solded_14_fbo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorystat',
            name='products_solded_14_fbs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorystat',
            name='products_solded_30_fbo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorystat',
            name='products_solded_30_fbs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorystat',
            name='products_solded_7_fbo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorystat',
            name='products_solded_7_fbs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorystat',
            name='profit_14_fbo',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorystat',
            name='profit_14_fbs',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorystat',
            name='profit_30_fbo',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorystat',
            name='profit_30_fbs',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorystat',
            name='profit_7_fbo',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorystat',
            name='profit_7_fbs',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorystat',
            name='sellers_count_14',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorystat',
            name='sellers_count_30',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorystat',
            name='sellers_count_7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorystat',
            name='sellers_solded_14_fbo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorystat',
            name='sellers_solded_14_fbs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorystat',
            name='sellers_solded_30_fbo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorystat',
            name='sellers_solded_30_fbs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorystat',
            name='sellers_solded_7_fbo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorystat',
            name='sellers_solded_7_fbs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorystat',
            name='top_14_fbo',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorystat',
            name='top_14_fbs',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorystat',
            name='top_30_fbo',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorystat',
            name='top_30_fbs',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorystat',
            name='top_7_fbo',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorystat',
            name='top_7_fbs',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productstat',
            name='priceU',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='parsing_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='price_avg_14',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='price_avg_30',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='price_avg_7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='product_10_profit_14_fbo',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='product_10_profit_14_fbs',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='product_10_profit_30_fbo',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='product_10_profit_30_fbs',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='product_10_profit_7_fbo',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='product_10_profit_7_fbs',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='product_1_profit_14_fbo',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='product_1_profit_14_fbs',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='product_1_profit_30_fbo',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='product_1_profit_30_fbs',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='product_1_profit_7_fbo',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='product_1_profit_7_fbs',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='products_solded_14_fbo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='products_solded_14_fbs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='products_solded_30_fbo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='products_solded_30_fbs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='products_solded_7_fbo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='products_solded_7_fbs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='profit_14_fbo',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='profit_14_fbs',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='profit_30_fbo',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='profit_30_fbs',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='profit_7_fbo',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='profit_7_fbs',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='top_14_fbo',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='top_14_fbs',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='top_30_fbo',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='top_30_fbs',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='top_7_fbo',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='top_7_fbs',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productstat',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['-parsed_at'], name='api_categor_parsed__5e63d0_idx'),
        ),
        migrations.AddIndex(
            model_name='productstat',
            index=models.Index(fields=['-parsing_id'], name='api_product_parsing_7d5d97_idx'),
        ),
        migrations.AddIndex(
            model_name='query',
            index=models.Index(fields=['-parsing_id'], name='api_query_parsing_b676cd_idx'),
        ),
    ]
