# Generated by Django 4.2 on 2023-05-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_productstat_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='calculated',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
