# Generated by Django 4.2 on 2023-05-19 05:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_category_calculated'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parsed_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), size=None), default=[], size=None),
        ),
        migrations.AddIndex(
            model_name='productstat',
            index=models.Index(fields=['-profit_30_fbo'], name='api_product_profit__c80501_idx'),
        ),
    ]
