# Generated by Django 4.2 on 2023-05-24 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_suplier_product_supplier_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suplier',
            new_name='Supplier',
        ),
    ]
