# Generated by Django 4.2 on 2023-05-26 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_rename_suplier_supplier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
