# Generated by Django 4.2 on 2023-05-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_delete_sale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorystat',
            options={'ordering': ['-parsing_id']},
        ),
        migrations.RemoveField(
            model_name='category',
            name='mongo_id',
        ),
        migrations.RemoveField(
            model_name='config',
            name='mongo_id',
        ),
        migrations.AddField(
            model_name='productstat',
            name='lost_profit',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
