# Generated by Django 4.2 on 2023-05-29 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_categorystat_options_remove_category_mongo_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productstat',
            old_name='lost_profit',
            new_name='profit_lost',
        ),
    ]
