# Generated by Django 4.2 on 2023-05-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_rename_lost_profit_productstat_profit_lost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productstat',
            old_name='profit_lost',
            new_name='profit_lost_fbo',
        ),
        migrations.AddField(
            model_name='productstat',
            name='profit_lost_fbs',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
