# Generated by Django 4.2.2 on 2023-06-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_product_basket_supplier_inn_supplier_ogrn_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['basket'], name='api_product_basket_3e02c6_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['wb_id'], name='api_supplie_wb_id_ba244c_idx'),
        ),
    ]
