# Generated by Django 4.2.2 on 2023-06-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_product_api_product_basket_3e02c6_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productstat',
            index=models.Index(fields=['parsing_id', 'product_id'], name='api_product_parsing_713aff_idx'),
        ),
    ]
