# Generated by Django 4.2.2 on 2023-06-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_productstat_api_product_parsing_713aff_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productstat',
            name='api_product_parsing_7d5d97_idx',
        ),
        migrations.RemoveIndex(
            model_name='productstat',
            name='api_product_profit__c80501_idx',
        ),
        migrations.AddIndex(
            model_name='productstat',
            index=models.Index(fields=['parsing_id'], name='api_product_parsing_c69ae7_idx'),
        ),
        migrations.AddIndex(
            model_name='productstat',
            index=models.Index(fields=['product_id', 'parsing_id'], name='api_product_product_fa7317_idx'),
        ),
        migrations.AddIndex(
            model_name='productstat',
            index=models.Index(fields=['profit_30_fbo'], name='api_product_profit__db6d31_idx'),
        ),
    ]
