# Generated by Django 4.2.4 on 2023-08-17 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_remove_productstat_api_product_parsing_7d5d97_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productstat',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='productstat',
            name='api_product_parsing_c69ae7_idx',
        ),
        migrations.RemoveIndex(
            model_name='productstat',
            name='api_product_product_fa7317_idx',
        ),
        migrations.RemoveIndex(
            model_name='productstat',
            name='api_product_profit__db6d31_idx',
        ),
    ]
