# Generated by Django 4.2.4 on 2023-09-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_alter_productstat_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='baskets_thread_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
