# Generated by Django 4.2.5 on 2023-09-21 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_config_baskets_thread_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='product_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
