# Generated by Django 4.2.5 on 2023-09-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_query_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='scoring',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
