# Generated by Django 4.2.5 on 2023-09-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_query_scoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstat',
            name='profit_30_fbo_grow',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
