# Generated by Django 4.2.5 on 2023-09-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_productstat_profit_30_fbo_grow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productstat',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='query',
            name='product_basket',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
