# Generated by Django 4.2.5 on 2023-09-29 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_alter_productstat_options_query_product_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='product_basket',
        ),
        migrations.RemoveField(
            model_name='query',
            name='product_name',
        ),
        migrations.AddField(
            model_name='query',
            name='first_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
    ]
