# Generated by Django 4.2.6 on 2023-10-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_remove_query_product_basket_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['supplier_id'], name='api_product_supplie_89b648_idx'),
        ),
    ]
