# Generated by Django 4.2.7 on 2023-11-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_product_api_product_supplie_89b648_idx'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='FboProfit30',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('product_id', models.IntegerField()),
        #         ('supplier_id', models.IntegerField(null=True)),
        #         ('parsing_id', models.IntegerField()),
        #         ('profit_30_fbo', models.DecimalField(decimal_places=2, max_digits=10)),
        #         ('features', models.JSONField()),
        #         ('root', models.CharField(max_length=255)),
        #     ],
        #     options={
        #         'db_table': 'view_fbo_profit_30',
        #         'managed': False,
        #     },
        # ),
        migrations.RunSQL("""
            CREATE MATERIALIZED VIEW view_fbo_profit_30 AS
                SELECT
                    api_productstat.product_id,
                    api_product.supplier_id,
                    api_productstat.parsing_id,
                    api_productstat.profit_30_fbo,
                    api_product.features,
                    api_product.root
                FROM
                    api_productstat
                    INNER JOIN api_product ON api_product.id = api_productstat.product_id
                WHERE
                    api_product.supplier_id IS NOT NULL AND
                    parsing_id >= CAST(extract(epoch from now()) AS INTEGER) - 60*60*24*30*2;
            CREATE INDEX idx_view_fbo_profit_30 ON view_fbo_profit_30(parsing_id, profit_30_fbo, root);
            REFRESH MATERIALIZED VIEW view_fbo_profit_30;
        """),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
