# Generated by Django 4.2.7 on 2023-12-07 06:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_fboprofit30_alter_product_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FboProfit30',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('supplier_id', models.IntegerField(null=True)),
                ('parsing_id', models.IntegerField()),
                ('profit_30_fbo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('features', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None), default=[], size=None)),
                ('root', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'view_fbo_profit_30',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='lemmas',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None), default=None, size=None),
        ),
    ]
