# Generated by Django 4.2.7 on 2023-12-07 07:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_fboprofit30_product_lemmas'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['lemmas'], name='api_product_lemmas_e55b59_idx'),
        ),
    ]
