# Generated by Django 5.0 on 2023-12-25 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_alter_product_lemmas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='first_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='first_product_category', to='api.product'),
        ),
        migrations.AddField(
            model_name='categorystat',
            name='scoring',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
