# Generated by Django 5.0 on 2023-12-30 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_category_first_product_categorystat_scoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='idx',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
