# Generated by Django 5.0.2 on 2024-02-21 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_category_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySaler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wb_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('page', models.IntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
    ]
